### ISSUE TITLE
Fixing problem with installation process

### ISSUE THREAD

**Issue by AndreyAttr** [AndreyAttr/Evo#46]
There is problem with absent **Webpack** JS configuration files which cause errors during installation. See remark onto this Wiki page:
[Wiki installation page](https://github.com/AndreyAttr/Evo/wiki/Installation)

**Comment by AndreyAttr** [comment]
The problem [from Wiki installation page](https://github.com/AndreyAttr/Evo/wiki/Installation)

> Remark: There will be Error: Cannot find module 'E:\Evo_Desktop\ClientWeb\webpack.config.js' connected with the fact that this webpack.config.js file absent into repository. But TypeScript files still transpile to JS. So, till it won't be fixed - add some 'space' into that webpack.config.ts file and webpack.config.js will be created. The same fix should be provided for Webpack/webpack.common.config.ts and webpack.dev.config.ts. After that Webpack start build the project

**Comment by tapy-lappy** [comment]
> molvwr.js?1c32:317 cannot get content from ../Evolution/Molecules/dna.pdb 404 Not Found

I found another problem - all functionality has worked except absent dna.pdb file. I figured out the problem was in gitignore file - there were rule *.pdb which ignores all the pdb files, So I added **_dna.pdb_** file to the project and added extra(exceptional) rule which denies the scope of main rule for specific folder(to eliminate this kind of problem when GIT doesn't see that there are changes in that directory, because PDB files there are source data files). Right now it looks like this:
```
*.pdb
!/ClientWeb/Evolution/Molecules/**/*.pdb
```
**Fixed**
